version: "2.4"
services:
  remote-interpreter:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    env_file: ".env.dev"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command:
      [
        "./scripts/start-development.sh",
      ]
  production:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "8000:8000"
    command:
      [
        "./scripts/start-production.sh",
      ]
  tests:
    image: python:3.8.3-slim
    env_file: .env.dev
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "pip install --no-cache-dir tox && tox"
