version: "2.4"
services:
  remote-interpreter:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command:
      [
        "./scripts/start-development.sh",
      ]
