FROM willianantunes/phonemizer:latest

WORKDIR /app

COPY Pipfile Pipfile.lock ./

RUN pip3 install --no-cache-dir --upgrade pip pipenv

RUN pipenv install --system --deploy --dev --ignore-pipfile

RUN rm Pipfile Pipfile.lock
