version: "3.8"

x-build: &dockerfile-dev-build
  context: .
  dockerfile: Dockerfile.dev

services:
  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  remote-interpreter:
    build: *dockerfile-dev-build
    env_file: .env.development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command:
      [
        "./scripts/wait-for-it.sh",
        "db:5432",
        "-t",
        "120",
        "--",
        "./scripts/start-development.sh",
      ]
  tests:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    env_file: .env.development
    depends_on:
      - db
    command:
      [
        "./scripts/wait-for-it.sh",
        "db:5432",
        "-t",
        "120",
        "--",
        "./scripts/start-tests.sh",
      ]
  lint:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    command: ["./scripts/start-lint.sh"]
  formatter:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    command: ["./scripts/start-formatter.sh"]
