// TODO: Launch an exception if some MUST HAVE variable is not present
const REDUX_DEVELOPER_TOOLS = process.env.REDUX_DEVELOPER_TOOLS === "true"
const GOOGLE_TAGMANAGER_ID = process.env.GOOGLE_TAGMANAGER_ID
const DISQUS_SHORTNAME = process.env.DISQUS_SHORTNAME
const SITE_URL = process.env.SITE_URL
const RECAPTCHA_TOKEN_HEADER = process.env.RECAPTCHA_TOKEN_HEADER
const RAVE_OF_PHONETICS_TRANSCRIBE_ENDPOINT = process.env.RAVE_OF_PHONETICS_TRANSCRIBE_ENDPOINT

module.exports = {
  REDUX_DEVELOPER_TOOLS,
  GOOGLE_TAGMANAGER_ID,
  SITE_URL,
  RECAPTCHA_TOKEN_HEADER,
  RAVE_OF_PHONETICS_TRANSCRIBE_ENDPOINT,
  DISQUS_SHORTNAME,
}
