// TODO: Launch an exception if some MUST HAVE variable is not present
const REDUX_DEVELOPER_TOOLS = process.env.REDUX_DEVELOPER_TOOLS === "true"

const DISQUS_SHORTNAME = process.env.DISQUS_SHORTNAME
const SITE_URL = process.env.SITE_URL
const RECAPTCHA_TOKEN_HEADER = process.env.RECAPTCHA_TOKEN_HEADER
const RAVE_OF_PHONETICS_TRANSCRIBE_ENDPOINT = process.env.RAVE_OF_PHONETICS_TRANSCRIBE_ENDPOINT
const RAVE_OF_PHONETICS_SUGGESTION_ENDPOINT = process.env.RAVE_OF_PHONETICS_SUGGESTION_ENDPOINT

const GTM_ID = process.env.GOOGLE_TAGMANAGER_ID
const GTM_INCLUDE_DEVELOPMENT = process.env.GTM_INCLUDE_DEVELOPMENT === "true"
const GTM_STANDARD_EVENT_NAME = process.env.GTM_STANDARD_EVENT_NAME || "rop-fe"
const GTM_SHOW_WHAT_WOULD_BE_SENT = process.env.GTM_SHOW_WHAT_WOULD_BE_SENT === "true"

const NETLIFY_CMS_LOCAL_BACKEND = process.env.NETLIFY_CMS_LOCAL_BACKEND === "true"
const NETLIFY_CMS_BACKEND_BRANCH = process.env.NETLIFY_CMS_BACKEND_BRANCH
const NETLIFY_CMS_BACKEND_API_ROOT = process.env.NETLIFY_CMS_BACKEND_API_ROOT
const NETLIFY_CMS_BACKEND_BASE_URL = process.env.NETLIFY_CMS_BACKEND_BASE_URL
const NETLIFY_CMS_BACKEND_AUTH_ENDPOINT = process.env.NETLIFY_CMS_BACKEND_AUTH_ENDPOINT
const NETLIFY_CMS_COMMIT_LABEL_PREFIX = process.env.NETLIFY_CMS_COMMIT_LABEL_PREFIX

module.exports = {
  REDUX_DEVELOPER_TOOLS,
  GTM_ID,
  GTM_STANDARD_EVENT_NAME,
  GTM_INCLUDE_DEVELOPMENT,
  GTM_SHOW_WHAT_WOULD_BE_SENT,
  SITE_URL,
  RECAPTCHA_TOKEN_HEADER,
  RAVE_OF_PHONETICS_TRANSCRIBE_ENDPOINT,
  RAVE_OF_PHONETICS_SUGGESTION_ENDPOINT,
  DISQUS_SHORTNAME,
  NETLIFY_CMS_LOCAL_BACKEND,
  NETLIFY_CMS_BACKEND_BRANCH,
  NETLIFY_CMS_BACKEND_API_ROOT,
  NETLIFY_CMS_BACKEND_BASE_URL,
  NETLIFY_CMS_BACKEND_AUTH_ENDPOINT,
  NETLIFY_CMS_COMMIT_LABEL_PREFIX,
}
