// TODO: Launch an exception if some MUST HAVE variable is not present
const REDUX_DEVELOPER_TOOLS = process.env.REDUX_DEVELOPER_TOOLS === "true"
const GOOGLE_TAGMANAGER_ID = process.env.GOOGLE_TAGMANAGER_ID
const DISQUS_SHORTNAME = process.env.DISQUS_SHORTNAME
const SITE_URL = process.env.SITE_URL
const RECAPTCHA_TOKEN_HEADER = process.env.RECAPTCHA_TOKEN_HEADER
const RAVE_OF_PHONETICS_TRANSCRIBE_ENDPOINT = process.env.RAVE_OF_PHONETICS_TRANSCRIBE_ENDPOINT

const NETLIFY_CMS_LOCAL_BACKEND = process.env.NETLIFY_CMS_LOCAL_BACKEND === "true"
const NETLIFY_CMS_BACKEND_BRANCH = process.env.NETLIFY_CMS_BACKEND_BRANCH
const NETLIFY_CMS_BACKEND_API_ROOT = process.env.NETLIFY_CMS_BACKEND_API_ROOT
const NETLIFY_CMS_BACKEND_BASE_URL = process.env.NETLIFY_CMS_BACKEND_BASE_URL
const NETLIFY_CMS_BACKEND_AUTH_ENDPOINT = process.env.NETLIFY_CMS_BACKEND_AUTH_ENDPOINT
const NETLIFY_CMS_COMMIT_LABEL_PREFIX = process.env.NETLIFY_CMS_COMMIT_LABEL_PREFIX

module.exports = {
  REDUX_DEVELOPER_TOOLS,
  GOOGLE_TAGMANAGER_ID,
  SITE_URL,
  RECAPTCHA_TOKEN_HEADER,
  RAVE_OF_PHONETICS_TRANSCRIBE_ENDPOINT,
  DISQUS_SHORTNAME,
  NETLIFY_CMS_LOCAL_BACKEND,
  NETLIFY_CMS_BACKEND_BRANCH,
  NETLIFY_CMS_BACKEND_API_ROOT,
  NETLIFY_CMS_BACKEND_BASE_URL,
  NETLIFY_CMS_BACKEND_AUTH_ENDPOINT,
  NETLIFY_CMS_COMMIT_LABEL_PREFIX,
}
