# Generated by Django 3.1.7 on 2021-03-11 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('language_tag', models.CharField(max_length=20, unique=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Language')),
                ('accent_or_dialect', models.CharField(blank=True, max_length=50, null=True, verbose_name='Accent/Dialect')),
                ('family', models.CharField(blank=True, max_length=50, null=True, verbose_name='Family')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('classification', models.CharField(choices=[('NOUN', 'Noun'), ('PRONOUN', 'Pronoun'), ('ADJECTIVE', 'Adjective'), ('VERB', 'Verb'), ('ADVERB', 'Adverb'), ('PREPOSITION', 'Preposition'), ('CONJUNCTION', 'Conjunction'), ('INTERJECTION', 'Interjection'), ('SYMBOL', 'Symbol'), ('UNDEFINED', 'Undefined')], default='UNDEFINED', max_length=15)),
                ('version', models.CharField(choices=[('V_1', 'Version 1'), ('V_2', 'Version 2'), ('V_3', 'Version 3'), ('V_4', 'Version 4')], default='V_1', max_length=3)),
                ('word_or_symbol', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('arpabet_phoneme', models.CharField(blank=True, max_length=128, null=True, verbose_name='ARPABET phoneme')),
                ('arpabet_phoneme_syllables', models.CharField(blank=True, max_length=128, null=True)),
                ('ipa_phonemic', models.CharField(blank=True, max_length=128, null=True, verbose_name='Phonemic transcription')),
                ('ipa_phonemic_syllables', models.CharField(blank=True, max_length=128, null=True)),
                ('ipa_phonetic', models.CharField(blank=True, max_length=128, null=True, verbose_name='Phonetic transcription')),
                ('ipa_phonetic_syllables', models.CharField(blank=True, max_length=128, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_entries', to='core.language')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dictionary',
            constraint=models.UniqueConstraint(fields=('language', 'classification', 'version', 'word_or_symbol'), name='unique_linguistic_set'),
        ),
    ]
