# Generated by Django 3.2 on 2021-04-09 13:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchedWord",
            fields=[
                ("id", models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name="Id")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("word_or_symbol", models.CharField(max_length=45)),
                ("language_tag", models.CharField(max_length=20)),
                ("ip_address", models.GenericIPAddressField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
